#!/usr/bin/env python3
"""Validate the workflow repository before commit or release."""

from __future__ import annotations

import json
import py_compile
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

REQUIRED = [
    "README.md",
    "AGENTS.md",
    "VERSION.json",
    "workflow/00_BOOT_SEQUENCE.md",
    "workflow/01_AUTHORITY_AND_CANON.md",
    "workflow/04_CHUNK_ORCHESTRATION.md",
    "workflow/06_RECOVERY_NEW_CHAT.md",
    "workflow/07_GIT_PROTOCOL.md",
    "workflow/08_AUTONOMOUS_EXECUTION.md",
    "workflow/11_DOCUMENT_CAPACITY.md",
    "stages/01_SYNOPSIS_CONTEXT.md",
    "stages/02_SCRIPT_PREFLIGHT.md",
    "stages/03_SCRIPT_CHUNK.md",
    "stages/04_SCRIPT_FULL_AUDIT.md",
    "stages/05_CHARACTER_CLASSIFICATION.md",
    "stages/06_CHARACTER_SHEET_TEXT.md",
    "stages/07_CHARACTER_IMAGE.md",
    "stages/08_VISUAL_PREPROCESS.md",
    "stages/09_VISUAL_CHUNK.md",
    "stages/10_VISUAL_FULL_AUDIT.md",
    "stages/11_FLOW.md",
    "stages/12_VIDEO.md",
    "stages/13_METADATA.md",
    "stages/14_RELEASE_AUDIT.md",
    "automation/build_flow_from_visual.py",
    "automation/build_video_from_visual.py",
    "templates/project_manifest.template.json",
    "templates/stage_status.template.json",
    "templates/flow_character_registry.template.json",
]

CORE_ASSERTIONS = {
    "README.md": ["한 편의 2~3시간", "21청크", "Medium", "보조 인물"],
    "stages/02_SCRIPT_PREFLIGHT.md": ["[CTA]", "[END]", "FIRM", "직접 대사"],
    "stages/07_CHARACTER_IMAGE.md": ["한글 고정명", "Medium", "보조 인물 이미지 0"],
    "stages/09_VISUAL_CHUNK.md": ["2~3문장", "직접 대사는 절대 누락", "영어 외형 앵커"],
    "stages/11_FLOW.md": ["Python", "N-1", "전체 재생성"],
    "stages/12_VIDEO.md": ["TTS", "립싱크", "BGM"],
    "stages/13_METADATA.md": ["의문형", "직설형", "숫자·역전형", "TIMELINE"],
    "workflow/11_DOCUMENT_CAPACITY.md": ["HIGH_CAPACITY_RISK", "DOCUMENT_CAPACITY_BLOCKED", "명시적 승인"],
}


def fail(message: str, errors: list[str]) -> None:
    errors.append(message)


def main() -> int:
    errors: list[str] = []

    for rel in REQUIRED:
        path = ROOT / rel
        if not path.is_file():
            fail(f"missing required file: {rel}", errors)

    for path in ROOT.rglob("*.json"):
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            fail(f"invalid JSON: {path.relative_to(ROOT)}: {exc}", errors)

    with tempfile.TemporaryDirectory() as temp_dir:
        for path in (ROOT / "automation").glob("*.py"):
            try:
                cfile = Path(temp_dir) / f"{path.stem}.pyc"
                py_compile.compile(str(path), cfile=str(cfile), doraise=True)
            except py_compile.PyCompileError as exc:
                fail(f"python compile failed: {path.name}: {exc}", errors)

    for rel, needles in CORE_ASSERTIONS.items():
        path = ROOT / rel
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for needle in needles:
            if needle not in text:
                fail(f"core rule missing in {rel}: {needle}", errors)

    tracked_noise = [p for p in ROOT.rglob("*") if "__pycache__" in p.parts]
    if tracked_noise:
        fail("__pycache__ present; remove generated bytecode before commit", errors)

    version = json.loads((ROOT / "VERSION.json").read_text(encoding="utf-8"))
    if version.get("format") != "single-feature-film":
        fail("VERSION.json format must be single-feature-film", errors)
    if version.get("default_script_chunks") != 21:
        fail("default_script_chunks must be 21", errors)
    if version.get("character_image_quality") != "Medium":
        fail("character image quality must be Medium", errors)

    if errors:
        print("WORKFLOW VALIDATION FAILED")
        for error in errors:
            print(f"- {error}")
        return 1

    print(f"WORKFLOW VALIDATION PASSED: {len(REQUIRED)} required files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
